{
  "Uuid": "2b558600-abc7-4178-b8f7-215be56370bc",
  "IsCustomNode": false,
  "Description": null,
  "Name": "Curve.PointAtParameter",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 1.0,
      "MinimumValue": 0.0,
      "StepValue": 0.1,
      "InputValue": 0.2,
      "Id": "e1d77bfb049644dc9a74561145eb0adf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "38b7d7a10028498abb637d338d163159",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "\"\"\"Copyright(c) 2019 by: duengocnguyen@gmail.com\"\"\"\r\n'https://www.youtube.com/channel/UCt2JhCDDFxpYho575WTMZ4g'\r\n\"\"\"________________Welcome to BIM3DM-DYNAMO API___________________\"\"\"\r\nimport clr \r\nimport sys\r\nimport math \r\nfrom System.Collections.Generic import *\r\n\r\nclr.AddReference(\"ProtoGeometry\")\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nclr.AddReference('RevitAPI')\r\nimport Autodesk\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\n\r\n\r\n#Preparing input from dynamo to revit\r\nelement = UnwrapElement(IN[0])\r\n\r\ndef getDBLineByLines(elements):\r\n    re = []\r\n    for i in elements:\r\n        crv = i.GeometryCurve\r\n        re.append(crv)\r\n    return re\r\n\r\nfactor = IN[1]\r\ndbLines = getDBLineByLines(element)\r\n\r\npoints = [dbLine.Evaluate(factor, True).ToPoint() for dbLine in dbLines]\r\n\r\nOUT = points",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "759bbac572254341980c712b91499bcd",
      "Inputs": [
        {
          "Id": "29faa4dd16b14e569a333daa73d060d5",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d5530d54f8124bd6b7a2ea748ab07c3b",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e9c055d4c57e4939875717a5c97fc99f",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementsSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "d541e8f5-36b8-4ae7-b8d1-00070a4f28e5-0389b160",
        "d541e8f5-36b8-4ae7-b8d1-00070a4f28e5-0389b18b",
        "d541e8f5-36b8-4ae7-b8d1-00070a4f28e5-0389b2aa",
        "d541e8f5-36b8-4ae7-b8d1-00070a4f28e5-0389b32e"
      ],
      "Id": "07628cd4460a46e694233de9e9b397e9",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7381646123db449db2216b1892a571a4",
          "Name": "Elements",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    }
  ],
  "Connectors": [
    {
      "Start": "38b7d7a10028498abb637d338d163159",
      "End": "d5530d54f8124bd6b7a2ea748ab07c3b",
      "Id": "a76b37e819e942d3800d91b26563f316"
    },
    {
      "Start": "7381646123db449db2216b1892a571a4",
      "End": "29faa4dd16b14e569a333daa73d060d5",
      "Id": "839f9ca0b4f04caf892f6d3cc2254889"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.10.1.3976",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "e1d77bfb049644dc9a74561145eb0adf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "param",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 83.0,
        "Y": 434.16179558191993
      },
      {
        "Id": "759bbac572254341980c712b91499bcd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 573.20734827977,
        "Y": 239.35083567811989
      },
      {
        "Id": "07628cd4460a46e694233de9e9b397e9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Select Model Elements",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 133.15354791075606,
        "Y": 159.0
      }
    ],
    "Annotations": [],
    "X": -21.465638186099568,
    "Y": 136.30768761863766,
    "Zoom": 0.91006380393143915
  }
}